<template>
  <v-card>
    <img
    src='https://cdn.vuetifyjs.com/images/carousel/planet.jpg'
    width="100%"
     />
    <v-card-title>ドローン</v-card-title>
    <v-card-text>どろーんです</v-card-text>
  </v-card>
</template>